name: Sebar TV Uploader

on:
  workflow_dispatch:

jobs:
  upload_video:
    runs-on: ubuntu-latest
    steps:
      - name: هێنانی کۆدەکان
        uses: actions/checkout@v3

      - name: ئامادەکردنی ژینگەی پایتۆن
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: دابەزاندنی چەکەکان
        run: pip install -r requirements.txt

      - name: هەڵدانی ڤیدیۆکە بۆ ناو قەڵاکە
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
        run: python upload.py
