name: Sebar_TV_SeekStreaming_Master

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'بەستەری ڤیدیۆ لێرە دابنێ'
        required: true
      file_name:
        description: 'ناوی فیلمەکە'
        required: true
      firebase_section:
        description: 'بەشەکە لە فایەربەیس'
        required: true
      firebase_id:
        description: 'ئایدی فیلمەکە'
        required: true

jobs:
  fast_upload:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗️ ئامادەکردنی چەکەکان
        run: |
          sudo apt-get update -qq
          pip install -q yt-dlp requests

      - name: ⬇️ داگرتنی ڤیدیۆ
        run: |
          yt-dlp --impersonate chrome \
                 --retries 50 \
                 --merge-output-format mp4 \
                 -o "video.mp4" \
                 "${{ github.event.inputs.video_url }}" || true

      - name: 🚀 ناردنی یەکسەر بۆ SeekStreaming و فایەربەیس
        env:
          FB_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          python3 -c "
          import os, requests
          
          # کلیلەکەی تۆ کە ناردت
          api_key = 'bad8b8344f2900c4f4ee94ea'
          fb_token = os.environ.get('FB_TOKEN')
          
          file_name = '${{ github.event.inputs.file_name }}'
          fb_section = '${{ github.event.inputs.firebase_section }}'
          fb_id = '${{ github.event.inputs.firebase_id }}'
          
          if os.path.exists('video.mp4'):
              print('١. وەرگرتنی سێرڤەری بەرزکردنەوە...')
              srv_res = requests.get(f'https://api.seekstreaming.com/api/upload/server?key={api_key}').json()
              upload_url = srv_res['result']
              
              print('٢. فڕێدانی فیلمەکە بۆ ناو سێرڤەر...')
              files = {'file': open('video.mp4', 'rb')}
              data = {'key': api_key}
              up_res = requests.post(upload_url, data=data, files=files).json()
              
              file_code = up_res['result'][0]['filecode']
              
              # دروستکردنی لینکی m3u8 بۆ پلەیەرەکەت
              direct_m3u8 = f'https://seekstreaming.com/hls/{file_code}.m3u8'
              print(f'لینک دروستکرا: {direct_m3u8}')
              
              # ٣. نوێکردنەوەی فایەربەیس
              db_url = f'https://sarko-43d61-default-rtdb.firebaseio.com/{fb_section}/{fb_id}.json?auth={fb_token}'
              payload = {
                  'title': file_name,
                  'translation': 'دۆبلاژ',
                  'url': direct_m3u8
              }
              requests.patch(db_url, json=payload)
              print('✅ تەواو! فیلمەکە چوو بۆ فایەربەیس و ١٧ هەزار کەسەکە دەتوانن بیبینن.')
          else:
              print('❌ هەڵە: ڤیدیۆکە دانەگیراوە.')
          "
